apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      nodeSelector:
        node-type: high-memory
      containers:
        - name: sonarqube
          image: sonarqube:community
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonarqube-volume
              mountPath: /opt/sonarqube/data
            - name: sonarqube-volume
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-volume
              mountPath: /opt/sonarqube/logs
      volumes:
       - name: sonarqube-volume
         persistentVolumeClaim:
           claimName: sonarqube-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: test
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
