apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medicure
  namespace: argocd
spec:
  project: k8s-deploy
  source:
    repoURL: https://github.com/Vijaya150/star-agile-health-care.git
    targetRevision: vijaya-dev
    path: argocd
  destination:
    server: https://172.31.89.84:6443
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
