apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: 100.26.183.71:30091/medicure-app:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: nexus-creds
